item_name: "&aNavigation"
interface_name: "&aSelect a server."
switch_item_name: "&aSwitch Server."
switching_message: "&aSwitching server..."
target_server: "survie"

no_permission: "§eYatsuuMenu >&a You do not have %permission% to run this command."
success_reload: "§eYatsuuMenu >&a The configuration has been reloaded."
