name: YatsuuMenu
version: '1.0'
main: fr.yatsuu.yatsuuMenu.YatsuuMenu
api-version: '1.21'
description: Plugin that lets you change servers via an interface.
author: Yatsuu

commands:
  ymreload:
    description: Reloads the plugin configuration.
    usage: /ymreload
    permission: yatsuumenu.command.reload
    default: op
