name: YatsuuMenu
version: '1.0'
main: fr.yatsuu.yatsuuMenu.YatsuuMenu
api-version: '1.21'
description: Plugin that lets you change servers via an interface.
author: Yatsuu

commands:
  ymload:
    description: Reloads the plugin configuration.
    usage: /ymload
    permission: yatsuumenu.command.ymload
    default: op
